# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-07-26 05:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('one_app', '0002_auto_20190726_0500'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='from',
            name='driver',
        ),
        migrations.RemoveField(
            model_name='from',
            name='rider',
        ),
        migrations.AddField(
            model_name='from',
            name='drivers',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='users_drivers', to='one_app.User'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='from',
            name='riders',
            field=models.ManyToManyField(related_name='users_riders', to='one_app.User'),
        ),
    ]
